### ISSUE TITLE
创建TG文件夹失败

### ISSUE THREAD

**Issue by lyrnya** [finalpi/wechat2tg#14]
[2024-06-01T04:27:25.932] [INFO] - [User is already connected!]
filter id 1
04:27:26 INFO 创建 TG 文件夹 
04:27:26 ERR 创建 TG 文件夹失败 RPCError: 400: FILTER_ID_INVALID (caused by messages.UpdateDialogFilter)
login... user error TypeError: Cannot read properties of undefined (reading 'id')
    at SetupServiceImpl.addToFolder (/app/dist/service/Impl/SetupServiceImpl.js:82:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/client/TelegramUserClient.js:74:21
    at async TelegramUserClient.start (/app/dist/client/TelegramUserClient.js:67:13)

**Comment by lyrnya** [comment]
打开自动创建群组会提示这个

**Comment by lyrnya** [comment]
我已经关闭了机器人的隐私模式

**Comment by lyrnya** [comment]
手动创建聊天文件夹解决，感谢大佬的项目，我这手机息屏wx完全不推消息，现在可算解决了
