### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by cloudy-sfu** [finalpi/wechat2tg#19]
After running `npm start`, there is an error:

```
> wechat2tg@1.0.0 start
> tsc && node dist/app.js NODE_ENV=production

/home/username/wechat2tg/node_modules/typescript/lib/tsc.js:92
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/username/wechat2tg/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

How to solve it? Thank you.

**Comment by areidx** [comment]
What`s your Node.js version? You can try using Node 18+.

**Comment by areidx** [comment]
I'm sorry you're encountering this issue. I tried with the same version of node as yours and didn't seem to have a problem:

```shell
❯ node -v
v20.15.0
❯ npm -v
10.7.0
❯ npm run build

 wechat2tg@1.0.0 build
 tsc
 
❯ npm start

wechat2tg@1.0.0 start
tsc && node dist/app.js NODE_ENV=production

File written successfully.
File written successfully.
[2024-07-06T00:54:26.492] [INFO] default - Wechat client start!

```

You could try starting with `npm run dev` to see if it launches. After that, you can try `npm run build;` and finally `npm start`.

I think I've encountered this issue before, but it should have been fixed (I'm not exactly sure what caused it, just that it got fixed). Please check if your code has been updated and, if possible, paste your `package.json` file for reference.

**Comment by areidx** [comment]
@cloudy-sfu I think you have run `npm i` using Node 12, and then use Node 20 to run other commands. You should delete the node_modules folder and then run `npm i` again. I hope that helps!

**Comment by areidx** [comment]
@cloudy-sfu I think you have run `npm i` using Node 12, and then used Node 20 to run other commands. You should delete the node_modules folder and then run `npm i` again. I have also updated the package.json file. Please update and try again. I hope that helps!
