### ISSUE TITLE
Forbidden by WeChat web version

### ISSUE THREAD

**Issue by cloudy-sfu** [finalpi/wechat2tg#20]
README.md says: `wechat4u` can work around the issue where some accounts are unable to log in to the WeChat web version.

However, this work-around is not successful. When I tried with my account, which is forbidden by web version but PC version is still available, it raises an error:

```
xxx@xxx:~/wechat2tg$ npm start

> wechat2tg@1.0.0 start
> tsc && node dist/app.js NODE_ENV=production

File written successfully.
File written successfully.
[2024-07-06T09:29:21.459] [INFO] default - Wechat client start!
[2024-07-06T09:29:50.263] [ERROR] default - error: AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:69:24)
    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:229:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:229:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

Usually after 5 minutes, there is an error message again. I think it's reasonable as the login attempt is time out.

```
[2024-07-06T09:34:54.116] [ERROR] default - error: AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:79:24)
    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:139:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
    '    at Object.notEqual (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:79:24)\n' +
    '    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:139:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

Following the traceback error message, I also open an issue at https://github.com/nodeWechat/wechat4u/issues/344

**Comment by areidx** [comment]
Maybe you can log in to UOS's WeChat once to lift this restriction. Both of my accounts can log in, but WeChat is called Weixin in China and WeChat in other countries. This is related to the registration account: those registered with a Chinese phone number are Weixin, but I'm not sure if this will affect UOS login.
