### ISSUE TITLE
tg2v，联系人对应错误

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#21]
在group里对某联系人(A)回复消息时，有概率(时间段性的)转发给其他的联系人(B)
没找到相关日志，如果有需要可以在下次复现的时候提供
特征(总共发生过两次):
- 在短时间连续发送多条消息的时候，都发送给错误的联系人
- 联系人B都是没有在tg联系过的，即没有创建相应群组，也没走过非group
版本号:1.0.9

**Comment by areidx** [comment]
你可以先尝试下v1.1.0，如果还有类似的情况尽量提供多点信息方便排查。

**Comment by Adlyq** [comment]
> 你可以先尝试下v1.1.0，如果还有类似的情况尽量提供多点信息方便排查。

了解，等待docker build
- 对docker不太熟悉，docker-compose logs只能输出尾部的部分日志，不知道如何完全输出到文件
- 日志中存在大量的重复错误，把想看的刷没了
```
wx2tg  | [2024-07-13T01:36:37.511] [ERROR] default - error: AssertionError [ERR_ASSERTION]: 1205 == 0
wx2tg  |     at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
wx2tg  |     at /app/node_modules/wechat4u/lib/core.js:326:24
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wx2tg  |     at async Promise.all (index 0) {
wx2tg  |   code: 2,
wx2tg  |   details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
wx2tg  |     '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
wx2tg  |     '    at /app/node_modules/wechat4u/lib/core.js:326:24\n' +
wx2tg  |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
wx2tg  |     '    at async Promise.all (index 0)'
wx2tg  | }
```
如上，能看到的日志全是这个

**Comment by areidx** [comment]
这个错误是调用太多获取用户信息接口导致的目前无解。docker 日志可以使用docker logs 滚动查看，另外可以把日志挂载到主机目录，容器内目录是logs这个。
