### ISSUE TITLE
群聊下，用户昵称显示错误

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#33]
如图
![Screenshot_2024-08-29-14-31-04-572_xyz.nextalone.nagram-edit.jpg](https://github.com/user-attachments/assets/daa80407-7b72-476f-a2b5-6c17ccc1d5ed)

![Screenshot_2024-08-29-14-30-39-236_com.tencent.mm-edit.jpg](https://github.com/user-attachments/assets/51db4949-6caa-4e72-b83a-69fb5e81d70d)

昵称不显示
版本1.2.1

**Comment by finalpi** [comment]
看下日志中是否有这行错误
`WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined`

**Comment by Adlyq** [comment]
![Screenshot_2024-08-29-15-33-43-517_com.termux-edit.jpg](https://github.com/user-attachments/assets/3f96cd8f-b9a9-4948-89b2-694ee9627976)

无

**Comment by finalpi** [comment]
error.log有这些日志吗
```
[ERROR] default - error: AssertionError [ERR_ASSERTION]: 1205 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:74:24)
    at /app/node_modules/wechat4u/lib/core.js:290:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:74:24)\n' +
    '    at /app/node_modules/wechat4u/lib/core.js:290:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)'
}
```

**Comment by Adlyq** [comment]
有的
![Screenshot_2024-08-29-15-56-43-978_com.termux.jpg](https://github.com/user-attachments/assets/bed41afe-1a1a-48f3-8e72-3c3f2faede38)

**Comment by finalpi** [comment]
已修复,请升级到v1.2.3版本

**Comment by Zerorigin** [comment]
这个问题在 v1.2.8 仍然存在
```
# grep contactRaw app.log
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +



# grep contactRaw error.log
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)
    '    at async PuppetWechat4u.contactRawPayload (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:565:28)\n' +
```

app.log:   https://pastebin.com/9uHKsadD
error.log:   https://pastebin.com/dC1w83tp
