### ISSUE TITLE
v2tg漏消息

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#39]
```
[2024-09-13T03:06:51.536] [ERROR] error - wechat2Tg uncaughtException FetchError: request to https://api.telegram.org/bot7210722171:[REDACTED]/getChat failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/app/node_modules/telegraf/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:529:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
[2024-09-13T03:19:34.982] [ERROR] default - error: GError: query must provide at least one key. current query is empty.
    at PuppetWechat4u.contactQueryFilterFactory (/app/node_modules/wechaty-puppet/dist/cjs/src/mixins/contact-mixin.js:120:23)
    at PuppetWechat4u.contactSearch (/app/node_modules/wechaty-puppet/dist/cjs/src/mixins/contact-mixin.js:67:41)
    at async WechatifiedContactImpl.findAll (/app/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:155:35)
    at async WechatifiedContactImpl.find (/app/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:110:29)
    at async Promise.all (index 0)
    at async PuppetWechat4u.<anonymous> (/app/node_modules/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:299:56) {
  code: 2,
  details: 'Error: query must provide at least one key. current query is empty.\n' +
    '    at PuppetWechat4u.contactQueryFilterFactory (/app/node_modules/wechaty-puppet/dist/cjs/src/mixins/contact-mixin.js:120:23)\n' +
    '    at PuppetWechat4u.contactSearch (/app/node_modules/wechaty-puppet/dist/cjs/src/mixins/contact-mixin.js:67:41)\n' +
    '    at async WechatifiedContactImpl.findAll (/app/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:155:35)\n' +
    '    at async WechatifiedContactImpl.find (/app/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:110:29)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async PuppetWechat4u.<anonymous> (/app/node_modules/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:299:56)'
}
```
9/13  11:06的消息，似乎是网络问题
希望可以在网络恢复后重发消息或发送失败不消耗消息留待重发

**Comment by finalpi** [comment]
根据日志内容修复了可能会导致消息丢失发生的一些错误,但是我本地无法复现这种情况,可以升级到v1.2.5版本再观察下还会不会有这种情况发生

**Comment by Adlyq** [comment]
```
wx2tg  | [2024-10-08T09:23:22.482] [INFO] - [User is already connected!]
wx2tg  | [2024-10-08T09:23:23.217] [INFO] - [Connecting to 91.108.56.155:443/TCPFull...]
wx2tg  | [2024-10-08T09:23:23.221] [INFO] - [Connection to 91.108.56.155:443/TCPFull complete!]
wx2tg  | [2024-10-08T09:23:53.222] [WARN] - [Disconnecting...]
wx2tg  | [2024-10-08T09:23:53.223] [INFO] - [Disconnecting from 91.108.56.155:443/TCPFull...]
wx2tg  | [2024-10-08T09:23:53.223] [INFO] - [connection closed]
wx2tg  | [2024-10-08T09:30:00.737] [ERROR] default - request to https://api.telegram.org/bot7210722171:[REDACTED]/sendMessage failed, reason: Client network socket disconnected before secure TLS connection was established
wx2tg  | uncaughtException TypeError: Cannot read properties of undefined (reading 'error_code')
wx2tg  |     at /app/dist/client/WechatClient.js:1045:28
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wx2tg  | uncaughtException TypeError: Cannot read properties of undefined (reading 'error_code')
wx2tg  |     at /app/dist/client/WechatClient.js:1196:32
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
**情况复现**

**Comment by finalpi** [comment]
似乎是tg的user侧的客户端未自动重连导致的,新版本已修复
