### ISSUE TITLE
最近很容易登录状态过期

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#45]
如题，一天得扫两三次码
这个`error: AssertionError [ERR_ASSERTION]: 400 != 400`有点奇怪
```
wx2tg  | [2024-10-08T10:41:42.340] [ERROR] default - error: AssertionError [ERR_ASSERTION]: 400 != 400
wx2tg  |     at Object.notEqual (/app/node_modules/wechat4u/lib/util/global.js:84:24)
wx2tg  |     at /app/node_modules/wechat4u/lib/core.js:126:24
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
wx2tg  |   code: 2,
wx2tg  |   details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
wx2tg  |     '    at Object.notEqual (/app/node_modules/wechat4u/lib/util/global.js:84:24)\n' +
wx2tg  |     '    at /app/node_modules/wechat4u/lib/core.js:126:24\n' +
wx2tg  |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
wx2tg  | }
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
wx2tg  | Error: TIMEOUT
wx2tg  |     at /app/node_modules/telegram/client/updates.js:250:85
wx2tg  |     at async attempts (/app/node_modules/telegram/client/updates.js:234:20)
wx2tg  |     at async _updateLoop (/app/node_modules/telegram/client/updates.js:183:17)
```

**Comment by linep4** [comment]
加一 我今天出现的

**Comment by linep4** [comment]
应该是网的问题，你搭在哪的，我迁到vps上了
