### ISSUE TITLE
视频通话消息没有提醒

### ISSUE THREAD

**Issue by nonlog** [finalpi/wechat2tg#50]
```
wx2tg  | [2024-11-12T00:39:22.931] [ERROR] default - 400: Bad Request: can't parse entities: Unsupported start tag "newcount" at byte offset 27
wx2tg  | [2024-11-12T02:23:41.418] [ERROR] default - 400: Bad Request: can't parse entities: Unsupported start tag "newcount" at byte offset 27
wx2tg  | [2024-11-12T03:21:33.095] [ERROR] default - 400: Bad Request: can't parse entities: Unsupported start tag "newcount" at byte offset 27
wx2tg  | File written successfully.
wx2tg  | [2024-11-12T03:44:28.200] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
wx2tg  | [2024-11-12T03:44:30.326] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
wx2tg  | [2024-11-12T03:44:30.329] [INFO] - [Using LAYER 184 for initial connect]
wx2tg  | [2024-11-12T03:45:03.373] [INFO] - [Phone migrated to 5]
wx2tg  | [2024-11-12T03:45:03.550] [INFO] - [Reconnecting to new data center 5]
wx2tg  | [2024-11-12T03:45:03.759] [WARN] - [Disconnecting...]
wx2tg  | [2024-11-12T03:45:03.759] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
wx2tg  | [2024-11-12T03:45:03.763] [INFO] - [Connecting to 91.108.56.128:80/TCPFull...]
wx2tg  | [2024-11-12T03:45:03.765] [INFO] - [connection closed]
wx2tg  | [2024-11-12T03:45:05.867] [INFO] - [Connection to 91.108.56.128:80/TCPFull complete!]
wx2tg  | [2024-11-12T03:45:05.876] [INFO] - [Using LAYER 184 for initial connect]
wx2tg  | [2024-11-12T03:45:27.815] [INFO] - [Signed in successfully as γ 11:45 AM ❀]
wx2tg  | uncaughtException Error: Could not find the input entity for {"userId":"7345200464","className":"PeerUser"}.
wx2tg  |          Please read https://docs.telethon.dev/en/stable/concepts/entities.html to find out more details.
wx2tg  |     at Object.getInputEntity (/app/node_modules/telegram/client/users.js:331:11)
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wx2tg  |     at async getInputFromResolve (/app/node_modules/telegram/tl/api.js:123:39)
wx2tg  |     at async VirtualClass.resolve (/app/node_modules/telegram/tl/api.js:473:43)
wx2tg  |     at async Object.invoke (/app/node_modules/telegram/client/users.js:35:5)
wx2tg  |     at async TelegramUserClient.createGroup (/app/dist/client/TelegramUserClient.js:183:28)
wx2tg  |     at async WeChatClient.message (/app/dist/client/WechatClient.js:589:32)
wx2tg  | [2024-11-12T03:48:31.228] [INFO] - [Connecting to 91.108.56.128:443/TCPFull...]
wx2tg  | [2024-11-12T03:48:31.432] [INFO] - [Connection to 91.108.56.128:443/TCPFull complete!]
wx2tg  | [2024-11-12T03:49:01.445] [WARN] - [Disconnecting...]
wx2tg  | [2024-11-12T03:49:01.451] [INFO] - [Disconnecting from 91.108.56.128:443/TCPFull...]
wx2tg  | [2024-11-12T03:49:01.459] [INFO] - [connection closed]
wx2tg  | [2024-11-12T03:53:23.731] [ERROR] default - tg bot error:  TypeError: Cannot read properties of undefined (reading 'payload')
wx2tg  |     at /app/dist/client/TelegramBotClient.js:1631:51
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
wx2tg  |   update_id: 187567710,
wx2tg  |   callback_query: {
wx2tg  |     id: '7261201506854221074',
wx2tg  |     from: {
wx2tg  |       id: 1690630220,
wx2tg  |       is_bot: false,
wx2tg  |       first_name: '∑',
wx2tg  |       last_name: '11:53 TUE ∈',
wx2tg  |       username: 'ohhlog',
wx2tg  |       language_code: 'en'
wx2tg  |     },
wx2tg  |     message: {
wx2tg  |       message_id: 732,
wx2tg  |       from: [Object],
wx2tg  |       chat: [Object],
wx2tg  |       date: 1731383602,
wx2tg  |       text: '请选择群组(点击回复)',
wx2tg  |       reply_markup: [Object]
wx2tg  |     },
wx2tg  |     chat_instance: '-169527508198716773',
wx2tg  |     data: 'search_13'
wx2tg  |   }
wx2tg  | }
wx2tg  | [2024-11-12T04:33:23.168] [INFO] - [Connecting to 91.108.56.128:443/TCPFull...]
wx2tg  | [2024-11-12T04:33:23.380] [INFO] - [Connection to 91.108.56.128:443/TCPFull complete!]
wx2tg  | [2024-11-12T04:33:23.827] [ERROR] default - 400: Bad Request: can't parse entities: Unsupported start tag "newcount" at byte offset 27
wx2tg  | [2024-11-12T04:33:53.381] [WARN] - [Disconnecting...]
wx2tg  | [2024-11-12T04:33:53.383] [INFO] - [Disconnecting from 91.108.56.128:443/TCPFull...]
wx2tg  | [2024-11-12T04:33:53.384] [INFO] - [connection closed]
wx2tg  | [2024-11-12T05:08:07.077] [ERROR] default - error: GError: not supported friend request message raw payload
wx2tg  |     at PuppetWechat4u.friendshipRawPayloadParser (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:1044:23)
wx2tg  |     at PuppetWechat4u.friendshipPayload (/app/node_modules/wechaty-puppet/dist/cjs/src/mixins/friendship-mixin.js:81:40)
wx2tg  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wx2tg  |     at async WechatifiedUserClass.ready (/app/node_modules/wechaty/dist/cjs/src/user-modules/friendship.js:180:24)
wx2tg  |     at async PuppetWechat4u.<anonymous> (/app/node_modules/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:197:33) {
wx2tg  |   code: 2,
wx2tg  |   details: 'Error: not supported friend request message raw payload\n' +
wx2tg  |     '    at PuppetWechat4u.friendshipRawPayloadParser (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:1044:23)\n' +
wx2tg  |     '    at PuppetWechat4u.friendshipPayload (/app/node_modules/wechaty-puppet/dist/cjs/src/mixins/friendship-mixin.js:81:40)\n' +
wx2tg  |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
wx2tg  |     '    at async WechatifiedUserClass.ready (/app/node_modules/wechaty/dist/cjs/src/user-modules/friendship.js:180:24)\n' +
wx2tg  |     '    at async PuppetWechat4u.<anonymous> (/app/node_modules/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:197:33)'
wx2tg  | }
wx2tg  | [2024-11-12T06:57:20.961] [ERROR] default - 400: Bad Request: can't parse entities: Unsupported start tag "newcount" at byte offset 27
wx2tg  | [2024-11-12T08:14:20.261] [ERROR] default - 400: Bad Request: can't parse entities: Unsupported start tag "newcount" at byte offset 27
wx2tg  | [2024-11-12T08:40:41.624] [INFO] - [Connecting to 91.108.56.128:443/TCPFull...]
wx2tg  | [2024-11-12T08:40:41.836] [INFO] - [Connection to 91.108.56.128:443/TCPFull complete!]
wx2tg  | [2024-11-12T08:41:11.840] [WARN] - [Disconnecting...]
wx2tg  | [2024-11-12T08:41:11.841] [INFO] - [Disconnecting from 91.108.56.128:443/TCPFull...]
wx2tg  | [2024-11-12T08:41:11.843] [INFO] - [connection closed]
```

普通消息是没问题的. 昨天删除重新部署了一下还是不行, 这是日志, 视频通话消息是 11/12 17:04 的, 好像没有相关日志

**Comment by finalpi** [comment]
> 还有一个小小的建议: 关于自动创建群组的命名, 目前是 `备注[昵称]` 的格式, 希望可以自定义格式

视频通话消息没有提醒的问题我这里无法复现。在 [v1.2.9](https://github.com/finalpi/wechat2tg?tab=readme-ov-file#docker-compose-recommended) 版本中添加了新的环境变量可以自定义用户创建群组时的名称格式
```
      # 自动创建微信群组的名称格式
      CREATE_ROOM_NAME: '#[topic]'
      # 自动创建联系人群组的名称格式
      CREATE_CONTACT_NAME: '#[alias]#[[name]]'
```

**Comment by Nimbly8836** [comment]
> 感谢更新，还有一个问题：“服务通知”里只有“微信快递服务”的消息能被转发，希望能修复一下。

"服务通知" 能截图一下吗？我的微信似乎没有这个东西

**Comment by hououinkami** [comment]
我也发现了视频通话在wx2tg中没有消息提醒

**Comment by Nimbly8836** [comment]
我尝试了都是没问题的，消息内容是未知的消息包含 "webwxvoipnotifymsg"  的就算视频或者语音通话；
```ts
else if (message.text() === 'webwxvoipnotifymsg') {
                    sendMessageBody.body = `${this.t('wechat.get')}${this.t('wechat.audioOrVideo')}, ${this.t('wechat.plzViewOnPhone')}`
                    this.tgClient.sendQueueHelper.addMessageWithMsgId(uniqueId, sendMessageBody)
                }
```
初步猜测可能是不同的语言消息内容不同

**Comment by Nimbly8836** [comment]
> 我尝试了都是没问题的，消息内容是未知的消息包含 "webwxvoipnotifymsg" 的就算视频或者语音通话；
> 
> ```ts
> else if (message.text() === 'webwxvoipnotifymsg') {
>                     sendMessageBody.body = `${this.t('wechat.get')}${this.t('wechat.audioOrVideo')}, ${this.t('wechat.plzViewOnPhone')}`
>                     this.tgClient.sendQueueHelper.addMessageWithMsgId(uniqueId, sendMessageBody)
>                 }
> ```
> 
> 初步猜测可能是不同的语言消息内容不同

我试过简体、繁体、英语，都是一样的消息，建议自己打印日志查看具体的消息是什么样子的

**Comment by hououinkami** [comment]
> > 我尝试了都是没问题的，消息内容是未知的消息包含 "webwxvoipnotifymsg" 的就算视频或者语音通话；
> > ```ts
> > else if (message.text() === 'webwxvoipnotifymsg') {
> >                     sendMessageBody.body = `${this.t('wechat.get')}${this.t('wechat.audioOrVideo')}, ${this.t('wechat.plzViewOnPhone')}`
> >                     this.tgClient.sendQueueHelper.addMessageWithMsgId(uniqueId, sendMessageBody)
> >                 }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 初步猜测可能是不同的语言消息内容不同
> 
> 我试过简体、繁体、英语，都是一样的消息，建议自己打印日志查看具体的消息是什么样子的

难道跟语言有关？我的是日语😂

**Comment by Nimbly8836** [comment]
> 我试了下语音电话和视频电话呼入，log中没有任何信息😂

我只是猜测是语言的关系，但是我尝试了日语是一样的文本（`webwxvoipnotifymsg`）；
由于未知类型的消息太多了代码中没有日志打印，你可以在开发分支使用 NODE_ENV=development 这个环境变量去打印

**Comment by HEAVEN1234000** [comment]
我用多台机器尝试后发现可能跟主机IP有关
